name: Deploy ML Model to SageMaker usingh CI/CD

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and Deploy to SageMaker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::921666318654:role/Abhi-OIDC-Role
        aws-region: us-east-1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t mlflow-model .

    - name: Tag and Push Docker image to ECR
      env:
        ECR_REGISTRY: 921666318654.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: myapp-repo
      run: |
        IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker tag mlflow-model $IMAGE_URI
        docker push $IMAGE_URI
        echo "ECR_IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      working-directory: ./terraform1
      run: terraform init

    - name: Terraform FMT
      working-directory: ./terraform1
      run: terraform fmt

    - name: Terraform validate
      working-directory: ./terraform1
      run: terraform validate

    - name: terraform Plan
      working-directory: ./terraform1
      run: terraform plan

    - name: Terraform Apply
      working-directory: ./terraform1
      env:
        TF_VAR_aws_region: us-east-1
        TF_VAR_sagemaker_role_arn: arn:aws:iam::921666318654:role/SageMakerExecutionRole
        TF_VAR_ecr_image_uri: ${{ env.ECR_IMAGE_URI }}
      run: terraform apply -auto-approve